import pandas as pd

def get_extention(filepath):
    return filepath.split(".")[-1]

def is_categorical(series, threshold=0.1):
    '''Identify if a column is categorical from the given values'''
    unique_values = series.nunique()
    length = len(series)
    if unique_values <= threshold * length:
        return True

def convert_label_map(predictions, label_map=None):
    '''
    Convert h2o predictions with label maps to original class ids
    Inputs:
        predictions -> List of predictions from h2o inference
        label_map -> Stored label map for the model generated by the AutoTrainer
    '''
    if label_map:
        converted = []
        label_map = {v:k for k,v in label_map.items()}
        for prediction in predictions:
            pred = label_map[prediction["predict"]]
            prediction = {label_map[key]: value for key,value in prediction.items() if key in label_map}
            prediction['predict'] = pred
            converted.append(prediction)
        return converted
    else:
        return predictions
    